export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const ADD_HISTORY = 'ADD_HISTORY';
export const RESET_HISTORY = 'RESET_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';

export const ADD_TWEETS = 'ADD_TWEETS';
