export const FETCH_DATA_LOADING = 'FETCH_DATA_LOADING';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';

export const ADD_HISTORY = 'ADD_HISTORY';
export const RESET_HISTORY = 'RESET_HISTORY';
export const REMOVE_HISTORY = 'REMOVE_HISTORY';

export const ADD_TWEETS = 'ADD_TWEETS';
export const ADD_TOP_TWEETS = 'ADD_TOP_TWEETS';
export const ADD_LATEST_TWEETS = 'ADD_LATEST_TWEETS';
export const ADD_PEOPLE_TWEETS = 'ADD_PEOPLE_TWEETS';
export const ADD_PHOTOS_TWEETS = 'ADD_PHOTOS_TWEETS';
export const ADD_VIDEOS_TWEETS = 'ADD_VIDEOS_TWEETS';
